### ISSUE TITLE
Wrong Data URL displayed in Collectory

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/collectory#68]
See, for example, https://collections.ala.org.au/dataResource/show/dr13282:

![image](https://user-images.githubusercontent.com/4694550/149689179-695c1f9d-d5d6-48d8-8798-5edcbf845318.png)

The file was uploaded correctly – and has been successfully loaded in pipelines – and the Location URL is correct, but the Data URL is not.

**Comment by djtfmartin** [comment]
Fixed on production - config updates deployed.

**Comment by peggynewman** [comment]
@djtfmartin  ...  the Data URL correctly on this DR is still not right, it should be a http link instead of:

file:////data/collectory/upload1642385640540/dwca-melu-avh-v1.1.zip

See https://collections.ala.org.au/dataResource/show/dr13282

**Comment by nielsklazenga** [comment]
@peggynewman, I "fixed" this by re-uploading the DwCA.

**Comment by peggynewman** [comment]
Lol, I wondered if that might be the way to fix it.
